<h1>Feedback Options</h1>

<form action="<?php echo $this->getFormAction(); ?>" method="POST">
<input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />

<?php
$results=Mage::getModel('shubhank_feedback/type')->getOptions();
for ($i=1; $i < 11 ; $i++) { 
	echo "Option ",$i," : <input type=\"text\" name=\"opt[$i]\" value=\"",$results[$i-1]['options'],"\"/><br/><br/>";
}

?>
<input type="submit" value="Save"/>
</form>